### ISSUE TITLE
tikz

### ISSUE THREAD

**Issue by Nhhoang-py** [martinpflaum/easylatex2image#1]
i can't correct convert  with content. 
content = r"""
\tikz{
\fill[pattern=north east lines] (0,0) rectangle (3,3);
}
"""
pattern not right.

**Comment by martinpflaum** [comment]
Hi😊. I am not sure if this is a bug or not. you need to add all packages that u are using. It actually just compiles the following latex code.


\documentclass[a4paper, 10pt]{article}
%%packages%%
\hoffset=-1in
\voffset=-1in
\setbox0\hbox{
%%content%%
}
\pdfpageheight=\dimexpr\ht0+\dp0\relax
\pdfpagewidth=\wd0
\shipout\box0
\stop


%%packages%% is what you replace with your packeges
%%content%% is the content 

So if all packages are included this should run correctly

**Comment by Nhhoang-py** [comment]
this is my code. can u help me! thank u!

Vào Th 4, 9 thg 11, 2022 vào lúc 18:50 martinpflaum <
***@***.***> đã viết:

**Comment by martinpflaum** [comment]
``` python
import easylatex2image
from easylatex2image import latex_to_image

packages_and_commands = r"""\usepackage[parfill]{parskip}
\usepackage[german]{varioref}
\usepackage{url}
\usepackage{amsmath} 
\usepackage{dcolumn}
\usepackage{tikz}
\usetikzlibrary{patterns}
\usetikzlibrary{shapes,arrows}
\usetikzlibrary{intersections}
\usepackage[all,cmtip]{xy}
"""

content = r"""

\tikz{
\fill[pattern=north east lines] (0,0) rectangle (3,3);
}
```

this should run. 


in pure latex it is:


``` latex
\documentclass{article}
\usepackage[utf8]{inputenc}

\title{sqee}\usepackage[parfill]{parskip}
\usepackage[german]{varioref}
\usepackage{url}
\usepackage{amsmath} 
\usepackage{dcolumn}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows}
\usetikzlibrary{patterns}
\usetikzlibrary{intersections}
\usepackage[all,cmtip]{xy}
\author{martin.pflaum.09.03.1999 }
\date{November 2022}

\begin{document}

\tikz{
\fill[pattern=north east lines] (0,0) rectangle (3,3);
}
\end{document}

```

**Comment by martinpflaum** [comment]
i am sry this actually seems not to work :'D also i don t know how to fix it quickly - my advice would be to look at this /easylatex2image/core.py it is the whole "library" and only 65 lines. you would need to change CONTENT_WRAPPER variable in line 6 - just compile and change it in overleaf. I porbably wont fix this on my own :'D sry

**Comment by martinpflaum** [comment]
The bug  probably is  that the package patterns is not passed to the hbox and the hbox kind of protects it s contents from this package. But I really don't know

**Comment by Nhhoang-py** [comment]
> The bug probably is that the package patterns is not passed to the hbox and the hbox kind of protects it s contents from this package. But I really don't know

thank u.

**Comment by martinpflaum** [comment]
ah got the bug 
\documentclass[a4paper, 10pt]{article}
\usepackage{url}
\usepackage{amsmath} 
\usepackage{dcolumn}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows}
\usetikzlibrary{patterns}
\usetikzlibrary{intersections}
\begin{document}

\hoffset=-1in
\voffset=-1in
\setbox0\hbox{
\tikz{
\fill[pattern=north east lines] (0,0) rectangle (3,3);
}
}

\pdfpageheight=\dimexpr\ht0+\dp0\relax
\pdfpagewidth=\wd0
\shipout\box0

\end{document}

will include this in the package

the /stop command causes the bug.

**Comment by martinpflaum** [comment]
oke updated the file

**Comment by Nhhoang-py** [comment]
> oke updated the file

No file C:\Users\nhocv\AppData\Local\Temp\tmpau4qbl35\something.aux.
! I can't write on file `C:\Users\nhocv\AppData\Local\Temp\tmpau4qbl35\somethin
g.aux'.
\document ...ate \openout \@mainaux \jobname .aux 
                                                  \immediate \write \@mainau...
l.7 \begin{document}
                    
it not run

**Comment by martinpflaum** [comment]
Sry I can't Programm on this more. But the code is only 65 lines!! In core.py I am sure u will figure it out-also latex code is now working.

**Comment by martinpflaum** [comment]
Good luck🤞
